import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { CanvasProvider } from '@/entities/canvas/model/canvas.context';

import './global.css';
import { SidebarProvider } from '@/shared/ui/shadcn/sidebar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CanvasProvider>
                    <SidebarProvider>{children}</SidebarProvider>
                </CanvasProvider>
            </body>
        </html>
    );
}
